name: CI-CD de test sur develop
on:
  pull_request:
    branches: [develop]


jobs:
  develop_build:
    runs-on: ubuntu-latest
    steps:
      - name: copie des fichiers
        uses: actions/checkout@v4
      - name: installation de nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: installation des paquets nodes
        run: npm ci
      - name: lancement du build
        run: npm run build
